### ISSUE TITLE
Outdated Install Instructions

### ISSUE THREAD

**Issue by dmgoncal** [cdanielmachado/transcript2flux#6]
Hi,

I have noticed that the instructions for installing the required software may be outdated, as the link for the MADE package is currently not working. 

I am interested in comparing the results of your study with my own, so I kindly request your assistance in obtaining the necessary resources to replicate your programming environment. Alternatively, I would appreciate any suggestions for obtaining the prediction and error values.

Thanks

**Comment by cdanielmachado** [comment]
Hi,

Yeah, it seems that the Papin has a new website and the old link doesn't work. I guess you can always try to contact them to get the code. Or implement it based on the description in their paper: https://www.frontiersin.org/articles/10.3389/fphys.2012.00299/full

**Comment by dmgoncal** [comment]
I'll see what I can do then. Cheers!
